package com.shanzha.moduls.sys.entity;

public class UserProfile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.id
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.gender
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.about_me
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private String aboutMe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.industry
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private String industry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.position
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.head_image
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private String headImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user_profile.introduction
	 * 
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	private String introduction;
	
	
	private String nickName;
	
	

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_user_profile.id
	 * 
	 * @return the value of sys_user_profile.id
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_user_profile.id
	 * 
	 * @param id
	 *            the value for sys_user_profile.id
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_user_profile.gender
	 * 
	 * @return the value of sys_user_profile.gender
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_user_profile.gender
	 * 
	 * @param gender
	 *            the value for sys_user_profile.gender
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_user_profile.about_me
	 * 
	 * @return the value of sys_user_profile.about_me
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public String getAboutMe() {
		return aboutMe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_user_profile.about_me
	 * 
	 * @param aboutMe
	 *            the value for sys_user_profile.about_me
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_user_profile.head_image
	 * 
	 * @return the value of sys_user_profile.head_image
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public String getHeadImage() {
		return headImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_user_profile.head_image
	 * 
	 * @param headImage
	 *            the value for sys_user_profile.head_image
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_user_profile.introduction
	 * 
	 * @return the value of sys_user_profile.introduction
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_user_profile.introduction
	 * 
	 * @param introduction
	 *            the value for sys_user_profile.introduction
	 * @mbg.generated Tue Dec 20 16:56:46 CST 2016
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getIndustry() {
		return industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

}